;;; archive-downloader-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from archive-downloader.el

(autoload 'archive-downloader-get "archive-downloader" "\
Download files from URL to LOCATION.

(fn URL LOCATION)" t)
(register-definition-prefixes "archive-downloader" '("archive-downloader-" "mwolson/archive-downloader-"))

;;; End of scraped data

(provide 'archive-downloader-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; archive-downloader-autoloads.el ends here
